### ISSUE TITLE
Using multidplyr within a function causes unexpected behaviour

### ISSUE THREAD

**Issue by avsdev-cw** [tidyverse/multidplyr#123] opened 2021-11-10 14:47 UTC
As per title:

```R
cluster <- multidplyr::new_cluster(parallel::detectCores())
someFunc <- function(data, cluster) {
  data %>%
    dplyr::group_by(cyl) %>%
    multidplyr::partition(cluster) %>%
    dplyr::summarise(avg_mpg = mean(mpg)) %>%
    dplyr::collect()
}
someFunc(mtcars, cluster)
```

If you are lucky 2 or more cores (main+workers) will randomly get used, if not then only the main thread gets used.

**Comment by greentheo** [comment] 2022-08-16 21:16
+1, it seems there's a lot of data copying and other things going on in the background.  Would love to see this resolved.

**Comment by hadley** [comment] 2022-09-25 15:37
Duplicate of #87

**Closed by hadley** 2022-09-25 15:37 UTC
