### ISSUE TITLE
Release multidplyr 0.1.1

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/multidplyr#127] opened 2021-11-30 13:26 UTC
Prepare for release:

* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_multidplyr.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] ~`revdepcheck::cloud_check()`~ :  no reverse dependencies
* [x] Update `cran-comments.md`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`

**Comment by romainfrancois** [comment] 2021-11-30 14:18
This is still getting these on win builder: https://win-builder.r-project.org/vNHpScdzEw6D/00check.log

````
* checking re-building of vignette outputs ... [17s] WARNING
Error(s) in re-building vignettes:
--- re-building 'multidplyr.Rmd' using rmarkdown
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
.... (many more)
````

**Comment by hadley** [comment] 2021-11-30 23:51
@gaborcsardi can't reproduce it on latest R-devel on windows, so I'll just turn the vignette into an article.

**Comment by gaborcsardi** [comment] 2021-12-01 09:25
It seems like an issue in vroom? This reproduces it with `gctorture()` (very slow!) on Windows R-devel (UCRT):

```r
library(dplyr)
library(nycflights13)
library(magrittr)

path <- tempfile()
dir.create(path)

gctorture(TRUE)

flights %>% 
  group_by(month) %>% 
  group_walk(~ vroom::vroom_write(.x, sprintf("%s/month-%02i.csv", path, .y$month)))
```

```
*** recursive gc invocation
*** recursive gc invocation
Error in vroom_write_(xx, file, delim, eol, na_str = na, col_names = col_names,  :
  cannot get ALTSTRING_ELT during GC
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
sive gc invo>c aion
** ecrsvegcinoctin
** ecursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

I think there is a good chance that you can also reproduce it on Unix, with `gctorture()`. If not let me know, and I can help debugging it on Windows or get you a VM.

**Comment by gaborcsardi** [comment] 2021-12-01 09:29
But yeah, moving it to an article unblocks the multidplyr release, and the vroom issue can be fixed later.

**Comment by gaborcsardi** [comment] 2021-12-01 10:29
Btw. if you need to disable GC (which is a pretty dangerous thing to do, I don't need to tell you), you can run your code inside a `DATAPTR()` method of a dummy class. `DATAPTR()` disables GC my default. 

Here is an example, search for "disable_gc": https://github.com/r-lib/cli/blob/1af3d91f64fff903685c58e94933210968f72570/src/progress-altrep.c#L35

**Comment by hadley** [comment] 2021-12-01 13:09
Filed an issue in vroom; I can just use write_csv here.

**Closed** 2021-12-01 22:02 UTC
